### ISSUE TITLE
Remove Multiple Labels

### ISSUE THREAD

**Issue by jburgess** [RobinJesba/GitHub-Labeler-Action#3]
It appears this action doesn't support removing multiple Labels. Ex:

existing labels: [ a, b, c, d ]

```yaml
    LABELS_TO_ADD: e,f
    LABELS_TO_REMOVE: a,b,c
```

expected labels: [d, e, f]

Possible to request this feature?

**Comment by RobinJesba** [comment]
@jburgess this should work. Can you share a sample workflow that you tried?
